name: CI - Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  # ==========================================================
  # 1. TESTS PYTHON
  # ==========================================================

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer les tests
        run: |
          pytest -v


  # ==========================================================
  # 2. BUILD DOCKER + PUSH AMAZON ECR
  # ==========================================================

  docker:
    needs: test

    # Le push vers AWS/ECR se fait uniquement
    # lorsqu'un commit est pousse sur main.
    #
    # Une Pull Request execute uniquement les tests.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-3
      ECR_REPOSITORY: titanic-dev-api

    steps:

      # ------------------------------------------------------
      # Recuperer le repository GitHub
      # ------------------------------------------------------

      - name: Recuperer le projet
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # Authentification GitHub Actions -> AWS via OIDC
      # ------------------------------------------------------

      - name: Configurer les credentials AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::435466090607:role/GitHubActionsTitanicRole
          aws-region: ${{ env.AWS_REGION }}
          allowed-account-ids: "435466090607"


      # ------------------------------------------------------
      # Authentification Docker -> Amazon ECR
      # ------------------------------------------------------

      - name: Connexion a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # ------------------------------------------------------
      # Build Docker compatible SageMaker + push ECR
      # ------------------------------------------------------

      - name: Construire et pousser image Docker vers ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |

          echo "--------------------------------------"
          echo "Construction de l'image Docker"
          echo "Repository : $ECR_REPOSITORY"
          echo "Tag        : $IMAGE_TAG"
          echo "Registry   : $ECR_REGISTRY"
          echo "--------------------------------------"

          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --output type=image,name=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG,push=true,oci-mediatypes=false \
            .

          echo "--------------------------------------"
          echo "Image envoyee avec succes dans ECR"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "--------------------------------------"